# Generated by Django 3.2.4 on 2021-06-30 13:54

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
